[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
# Version is determined from git tags
# For tags: v2025.3.0 -> 2025.3.0
# For main branch: 2025.3.0.dev3+gXXXXXXX
local_scheme = "no-local-version"