# mapget: A client/server application for map data retrieval.

# From: trace, debug, info, warn, error, critical. Overrides MAPGET_LOG_LEVEL.
log-level="trace"

# Server to connect to in format <host:port>.
fetch.server="127.0.0.1:61852"
# Map to retrieve.
fetch.map="Tropico"
# Layer of the map to retrieve.
fetch.layer="WayLayer"
# Tile of the map to retrieve. Can be specified multiple times.
fetch.tile="12345"
