# Invoked on each packaging build, so new/deleted Markdown needs no reconfigure.
if(NOT REGISTRY OR NOT DESTINATION)
  message(FATAL_ERROR "MCP help staging requires REGISTRY and DESTINATION")
endif()
file(READ "${REGISTRY}" registry)
file(REMOVE_RECURSE "${DESTINATION}")
file(MAKE_DIRECTORY "${DESTINATION}")
string(JSON count LENGTH "${registry}")
if(count GREATER 0)
  math(EXPR last "${count} - 1")
  foreach(index RANGE ${last})
    string(JSON component MEMBER "${registry}" ${index})
    string(JSON source GET "${registry}" "${component}")
    file(GLOB_RECURSE documents RELATIVE "${source}" "${source}/*.md")
    foreach(document IN LISTS documents)
      get_filename_component(parent "${document}" DIRECTORY)
      file(MAKE_DIRECTORY "${DESTINATION}/${component}/${parent}")
      configure_file("${source}/${document}" "${DESTINATION}/${component}/${document}" COPYONLY)
    endforeach()
  endforeach()
endif()
