name: Deploy

on:
  workflow_dispatch: {}

jobs:
  deploy:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [macos-latest, ubuntu-latest, windows-2019]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch
        # Use official download-artifact action once fixed:
        # https://github.com/actions/download-artifact/issues/3
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: cmake.yaml
          name: mapget-py${{ matrix.python-version }}-${{ matrix.os }}
          path: dist/
      - name: Upload
        env:
          KE_PYPI_TOKEN: ${{ secrets.KE_PYPI_TOKEN }}
        run: |
          echo "Initial state:"
          echo "=============="
          cd dist/
          ls .
          echo "Uploading..."
          echo "============"
          python3 -m venv venv
          . venv/bin/activate
          pip install twine
          twine upload \
            --non-interactive \
            --skip-existing \
            --verbose \
            --disable-progress-bar \
            -u "__token__" \
            -p "${KE_PYPI_TOKEN}" \
            *.whl
